[package]
name = "feeds-to-pocket"
version = "0.1.6"
authors = ["Francis Gagn√© <fragag1@gmail.com>"]
edition = "2021"
description = "Sends items from your RSS and Atom feeds to your Pocket list."
repository = "https://github.com/FraGag/feeds-to-pocket"
readme = "README.md"
keywords = ["atom", "feed", "pocket", "rss", "syndication"]
license = "MIT/Apache-2.0"
exclude = [".travis.yml"]

[dependencies]
atom_syndication = "0.6.0"
clap = "2.32.0"
quick-error = "1.2.2"
reqwest = "0.9.4"
rss = "1.6.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
serde_yaml = "0.8.7"
url = "1.7.2"
url_serde = "0.2.0"
